name: trashtrack_user
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.3.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  meta: ^1.12.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  awesome_dialog: ^3.2.1
  intl: ^0.19.0
  google_maps_flutter: ^2.9.0
  location: ^5.0.0
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.0
  awesome_notifications: ^0.9.3+1
  shared_preferences: ^2.3.2
  firebase_storage: ^12.2.0
  image_picker: ^1.1.2
  http: ^1.2.2
  flutter_echarts: ^2.5.0
  auto_size_text: ^3.0.0
  google_sign_in: ^6.2.1
  sign_in_button: ^3.2.0
  geolocator: ^13.0.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
